# Generated by Django 5.0.7 on 2024-07-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id_mahasiswa', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=7)),
                ('nama_mahasiswa', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(max_length=12)),
                ('program_studi', models.CharField(max_length=25)),
            ],
        ),
    ]
